runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /_ah/api/.*
  script: api.google_cloud_endpoints.services_api.api

- url: /.*
  script: frontend.home.app

libraries:
- name: webapp2
  version: 2.5.2
- name: pycrypto
  version: "latest"
- name: ssl
  version: 2.7.11

env_variables:
  ENDPOINTS_SERVICE_NAME: simple-analytics-ws.appspot.com
  ENDPOINTS_SERVICE_VERSION: 2018-09-17r0
