import google.appengine.ext.ndb as ndb


class Event(ndb.Model):
    """Datastore entity representing an event"""

    # id = autogenerated value
    content_id = ndb.StringProperty(indexed=True, required=True)
    time = ndb.DateTimeProperty(indexed=False, required=True)

    user_ip = ndb.StringProperty(indexed=True, required=True)
    user_user_agent = ndb.StringProperty(indexed=False, required=True)
    user_location = ndb.StringProperty(indexed=False, required=False)

    added_date = ndb.DateTimeProperty(auto_now_add=True)


class Content(ndb.Model):
    """Datastore entity representing an external content"""

    # id = content_id
    content_name = ndb.StringProperty(indexed=False, required=True)
